all: unorderedhttest

unorderedhttest: unorderedhttest.cpp
	g++ -std=c++11 -o unorderedhttest unorderedhttest.cpp HashNodeChain.h HashNodeChain.cpp HashTableChain.h HashTableChain.cpp

clean:
	rm *.o unorderedhttest